name: ICE5-MultiPLatform

on:
    release:
        types: [created]
    workflow_dispatch: #comment
    pull_request:
        branches: ["main"]

jobs:
  ubuntu_job:
    name: Ubuntu Job Running Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print OS Info
        run: uname -a

      - name: Create Text File
        run: echo "Hello, World" > testfile.txt

      - name: Display File
        run: cat testfile.txt
  windows_job:
    name: Windows Job Running Latest
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print OS Info
        run: systeminfo

      - name: Create Text File
        run: echo "Hello, World" > testfile.txt

      - name: Display File
        run: Get-Content testfile.txt
        
  macos_job:
    name: macOS Job Running Latest
    runs-on: macos-latest
    steps:
        - name: Checkout Code
        - uses: actions/checkout@v4

        - name: Print OS Info
        - run: uname -a

        - name: Create Text File
        - run: echo "Hello, World" > testfile.txt

        - name: Display File
        - run: cat testfile.txt